# Generated by Django 2.2 on 2021-03-23 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('rut', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=30)),
                ('image_ruta', models.ImageField(upload_to='servicio')),
                ('id_cot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.Cotizacion')),
            ],
        ),
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('centro', models.CharField(max_length=40)),
                ('dir_centro', models.CharField(max_length=50)),
                ('id_emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.Empresa')),
            ],
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='id_repr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.Representante'),
        ),
    ]
