# Generated by Django 2.2 on 2021-03-25 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='cantidad',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='region',
            field=models.CharField(choices=[('XV', 'Región de Arica y Parinacota'), ('I', 'Región de Tarapacá'), ('II', 'Región de Antofagasta'), ('III', 'Región de Atacama'), ('IV', 'Región de Coquimbo'), ('V', 'Región de Valparaíso'), ('RM', 'Región Metropolitana de Santiago'), ('VI', 'Región del Libertador General Bernardo OHiggins'), ('VII', 'Región del Maule'), ('XVI', 'Región del Ñuble'), ('VIII', 'Región del Biobío'), ('IX', 'Región de La Araucania'), ('XIV', 'Región de Los Ríos'), ('X', 'Región de Los Lagos'), ('XI', 'Región de Aysén del General Carlos Ibáñez del Campo'), ('XII', 'Región de Magallanes y la Antártica Chilena')], default='', max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='rut',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='representante',
            name='apellido',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='representante',
            name='centro',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='representante',
            name='ciudad_centro',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='representante',
            name='nombre',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='representante',
            name='telefono',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='nombre',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
