# Generated by Django 2.2 on 2021-03-23 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='represante',
            new_name='representante',
        ),
    ]
