# Generated by Django 2.2 on 2021-03-23 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='id_cot',
        ),
        migrations.AddField(
            model_name='servicio',
            name='id_cot',
            field=models.ManyToManyField(to='app_1.Cotizacion'),
        ),
    ]
