# Generated by Django 2.2 on 2021-04-06 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='image_ruta',
            new_name='imagen_ruta',
        ),
    ]
