# Generated by Django 2.2 on 2021-04-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_auto_20210406_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='region',
            field=models.CharField(choices=[('CH', 'Chile'), ('AR', 'Argentina'), ('EU', 'Estados Unidos'), ('CA', 'Canada'), ('ES', 'España'), ('PO', 'Portugal'), ('AU', 'Australia'), ('SW', 'Suecia'), ('NO', 'Noruega')], max_length=4),
        ),
    ]
