# Generated by Django 2.2 on 2021-03-26 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_auto_20210325_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='serv_cot',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
