# Generated by Django 2.2 on 2021-04-08 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0003_auto_20210408_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='region',
            new_name='Pais',
        ),
    ]
