# Generated by Django 2.2 on 2021-03-26 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0003_auto_20210326_0149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='nombre',
            new_name='Nombre',
        ),
        migrations.AlterField(
            model_name='serv_cot',
            name='nuevo_precio',
            field=models.FloatField(max_length=30),
        ),
    ]
